SELECT
Q_EST_E_Summary_Using_Designated_Length.Year, 
Q_EST_E_Summary_Using_Designated_Length.BED,
FormatNumber([SumOfArea_Sq_NM],1) 
	AS SQNM_in_Bed,
Q_EST_E_Summary_Using_Designated_Length.Number_of_Tows,
Q_EST_E_Summary_Using_Designated_Length.Total_NM_Towed,
[Q_EST_E_Summary_Using_Designated_Length].[Number_of_Tows]*(0.001316656)
	AS AreaSwept,
Q_EST_E_Summary_Using_Designated_Length.Raw_Count_Scallops,
Q_EST_E_Summary_Using_Designated_Length.Raw_Wt_KG_Scallops,
Q_EST_E_Summary_Using_Designated_Length.Count_Scal_per_NM,
Q_EST_E_Summary_Using_Designated_Length.Wt_KG_Scal_per_NM,
Q_EST_E_Summary_Using_Designated_Length.Mean_Count_Scal_per_NM,
Q_EST_E_Summary_Using_Designated_Length.Mean_Wt_KG_Scal_per_NM,
Q_EST_E_Summary_Using_Designated_Length.Var_of_Count,
Q_EST_E_Summary_Using_Designated_Length.Var_of_Weight,

Count(DATA_SCALLOP_SURVEY_STATIONS.BED) AS Big_N

INTO Q_EST_G_table

FROM Q_EST_F INNER JOIN (Q_EST_E_Summary_Using_Designated_Length INNER JOIN DATA_SCALLOP_SURVEY_STATIONS ON Q_EST_E_Summary_Using_Designated_Length.BED = DATA_SCALLOP_SURVEY_STATIONS.BED) ON (Q_EST_F.BED = DATA_SCALLOP_SURVEY_STATIONS.BED) AND (Q_EST_F.BED = Q_EST_E_Summary_Using_Designated_Length.BED)

GROUP BY Q_EST_E_Summary_Using_Designated_Length.Year, Q_EST_E_Summary_Using_Designated_Length.BED, FormatNumber([SumOfArea_Sq_NM],1), Q_EST_E_Summary_Using_Designated_Length.Number_of_Tows, Q_EST_E_Summary_Using_Designated_Length.Total_NM_Towed, [Q_EST_E_Summary_Using_Designated_Length].[Number_of_Tows]*(0.001316656), Q_EST_E_Summary_Using_Designated_Length.Raw_Count_Scallops, Q_EST_E_Summary_Using_Designated_Length.Raw_Wt_KG_Scallops, Q_EST_E_Summary_Using_Designated_Length.Count_Scal_per_NM, Q_EST_E_Summary_Using_Designated_Length.Wt_KG_Scal_per_NM, Q_EST_E_Summary_Using_Designated_Length.Mean_Count_Scal_per_NM, Q_EST_E_Summary_Using_Designated_Length.Mean_Wt_KG_Scal_per_NM, Q_EST_E_Summary_Using_Designated_Length.Var_of_Count, Q_EST_E_Summary_Using_Designated_Length.Var_of_Weight;
