SELECT
DATA_EVENTS_SCALLOP_DREDGE.USED_IN_ESTIMATE,
DATA_EVENTS_SCALLOP_DREDGE.BED,
DATA_EVENTS_SCALLOP_DREDGE.EVENT_ID,
DATA_EVENTS_SCALLOP_DREDGE.YEAR,
DATA_EVENTS_SCALLOP_DREDGE.PROJECT_CODE,
NZ(DSUM("[Count]","[DATA_CATCHCOMP_SCALLOP_DREDGE]", "[EVENT_ID] = '" & [DATA_EVENTS_SCALLOP_DREDGE.EVENT_ID] & "'
	AND [SPECIES_CODE] = '850'
	AND [CONDITION_CODE] = '01' "
	),0) AS SumOfCOUNT,
NZ(DSUM("[SAMPLE_WT_KG]","[DATA_CATCHCOMP_SCALLOP_DREDGE]", "[EVENT_ID] = '" & [DATA_EVENTS_SCALLOP_DREDGE.EVENT_ID] & "'
	AND [SPECIES_CODE] = '850'
	AND [CONDITION_CODE] = '01' "
	),0) AS SumOfSAMPLE_WT_KG

INTO Q_EST_C_CC_Scallop_Summary

FROM DATA_EVENTS_SCALLOP_DREDGE LEFT JOIN DATA_CATCHCOMP_SCALLOP_DREDGE 
	ON DATA_EVENTS_SCALLOP_DREDGE.EVENT_ID = DATA_CATCHCOMP_SCALLOP_DREDGE.EVENT_ID

GROUP BY DATA_EVENTS_SCALLOP_DREDGE.USED_IN_ESTIMATE,
	DATA_EVENTS_SCALLOP_DREDGE.BED,
	DATA_EVENTS_SCALLOP_DREDGE.EVENT_ID,
	DATA_EVENTS_SCALLOP_DREDGE.YEAR,
	DATA_EVENTS_SCALLOP_DREDGE.PROJECT_CODE
	

HAVING (DATA_EVENTS_SCALLOP_DREDGE.USED_IN_ESTIMATE="YES"
	AND DATA_EVENTS_SCALLOP_DREDGE.Year>"1995") 
	

ORDER BY DATA_EVENTS_SCALLOP_DREDGE.EVENT_ID;
