SELECT 
Q_EST_C_CC_Scallop_Summary.EVENT_ID,
Q_EST_C_CC_Scallop_Summary.Year,
Q_EST_C_CC_Scallop_Summary.PROJECT_CODE,
Q_EST_C_CC_Scallop_Summary.SumOfCOUNT,
Q_EST_C_CC_Scallop_Summary.SumOfSAMPLE_WT_KG,
DATA_EVENTS_SCALLOP_DREDGE_1.USED_IN_ESTIMATE,
DATA_EVENTS_SCALLOP_DREDGE_1.STATION_ID,
DATA_EVENTS_SCALLOP_DREDGE_1.BED,
DATA_EVENTS_SCALLOP_DREDGE_1.TOW_LENGTH_DESIGNATED,
[SumOfCOUNT]*(1/[TOW_LENGTH_DESIGNATED]) AS St_Count_Desig_Lngth,
[SumOfSAMPLE_WT_KG]*(1/[TOW_LENGTH_DESIGNATED]) AS St_Weight_Desig_Lngth

INTO Q_EST_D_Standardized_Catch

FROM DATA_EVENTS_SCALLOP_DREDGE AS DATA_EVENTS_SCALLOP_DREDGE_1 
	INNER JOIN Q_EST_C_CC_Scallop_Summary
		ON DATA_EVENTS_SCALLOP_DREDGE_1.EVENT_ID = Q_EST_C_CC_Scallop_Summary.EVENT_ID

WHERE (((DATA_EVENTS_SCALLOP_DREDGE_1.USED_IN_ESTIMATE)="YES"));
