---
title: "2016 Statewide Weathervane Scallop Survey Summary"
author:
- affiliation: Alaska Department of Fish and Game, Juneau, AK
  email: ben.williams@alaska.gov
  name: Benjamin C. Williams and Katie Palof
- affiliation: Alaska Department of Fish and Game, Homer, AK
  name: Josh Mumm
date: ''
output:
  html_document:
    toc: yes
csl: canjfas.csl
css: markdown4.css
bibliography: scallop_survey_bibfile.bib
---
#ABSTRACT  

#INTRODUCTION  

#GENERAL BIOLOGY  

#OBJECTIVES  
##Primary  
 1. Estimate catch rates and abundance of scallops by survey area with a coefficient of variation (CV) ≤ 20%.
 2. Collection of biological data (e.g., shell height, meat weight, age) for estimation of growth, mortality, and biomass.  

##Secondary  
 1. Record incidental catch (numbers and weight) of commercially important species and scallop predators.
 
##Tertiary  
 1. Address particular area management concerns.
 2. Special short term projects.
 
#METHODS  

Scallop abundance estimation based upon area-swept calculations where scallop density $d_i$ is calculated as:

$$d_i=\frac{c_i}{a_i},$$  
where  
$$a_i=l_i\cdot dw\cdot Q,$$  
and  
$$\bar d = \frac{1}{s}\sum_{i=1}^{s} d_i.$$

Density variance is calculated as  

$$
\hat{\sigma }^{2}_{\bar d} = \frac{1}{s-1}\sum \left ( d_i-\bar{d} \right )^2
$$

And 95% confidence intervals calculated as:  

$$
ci = \pm t_{\alpha=0.05}, n=df-1\frac{\hat{\sigma}_d}{\sqrt{s}}
$$

where: 

$c_i$ = the catch of a species, either as abundance or weight, in sample haul *i*,  
$a_i$ = the nmi^2^ sampled in haul *i*,  
$l_i$ = the nmi towed for sample haul *i*,  
*dw* = the dredge width in nmi,   
*Q* = dredge efficency, and   
*s* = the number of stations sampled.  

An estimate of the surveyed population $\hat{N}$ will be calculated by expanding $\bar{d}$ over the defined bed area *A* encompassing all grid cells as: 

$$
\hat{N}=A\bar{d}.
$$

Variance of the surveyed population was estimated [@Seber1982] by

$$
\hat{\sigma }^{2}_{\hat{N}}=S^2\frac{s^2}{s}(1-(\frac{s}{S})),
$$

where:  

$$
S=\frac{A}{\bar{a} }.
$$

A preliminary *Q* of 0.83 calculated from the Kayak Island beds in 2004 [@Gustafson2012] was used in lieu of bed specific efficiencies. 

#RESULTS  
```{r, echo=F, message=F, warning=F}
library(knitr)
a <- read.csv('../data/variances')
library(tidyverse)
options(scipen=9999) # remove scientific notation
a %>% mutate(N=round(N),UL=round(UL),LL=round(LL),N_wt=round(N_wt),UL_wt=round(UL_wt),LL_wt=round(LL_wt)) %>% select(Bed, size,N,UL,LL,N_wt,UL_wt,LL_wt) %>% kable()

a %>% filter(Bed=='WK1', size=='all') -> wk1
```


The western Kayak Island abundance estimate of all scallops was ```r round(wk1$N)``` with 95% CI of ```r round(wk1$LL)``` - ```r round(wk1$UL)```.

#DISCUSSION  

#REFERENCES


